[project]
name = "backend"
version = "0.1.0"
description = "Backend for explain that code"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "langchain>=0.3.26",
    "langchain-ollama>=0.3.3",
]
